map_server:
  ros__parameters:
      use_sim_time: false
      yaml_filename: ''

keepout_mask_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""
    topic_name: "/keepout_mask"

costmap_filter_info_server:
  ros__parameters:
    use_sim_time: false
    type: 0
    filter_info_topic: "/costmap_filter_info"
    mask_topic: "/keepout_mask"
    base: 0.0
    multiplier: 1.0